# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cauldron',
                'doc_host': 'https://bhargavchippada.github.io',
                'git_url': 'https://github.com/bhargavchippada/cauldron',
                'lib_path': 'cauldron'},
  'syms': {'cauldron.core': {'cauldron.core.foo': ('core.html#foo', 'cauldron/core.py')}}}
